### PR TITLE
Add chart row limit warning tooltip

### LINKED ISSUE #144: Row limit warning for charts
## Context

As pointed out by @havef and discussed in #142, Datasette sets limits on the number of rows returned by SQL queries (setting `max_returned_rows` defaulting to 1000). This can have an impact on rendered charts when more than `max_returned_rows` are expected to be displayed.

## Technical details

To be able to detect when a data truncation occurs, all charts should be using the JSON API with the `_shape=objects` query argument, allowing to get the `truncated` boolean value.

For instance, this query:

```
https://datasette-dashboards-demo.vercel.app/jobs.json?sql=SELECT date(date) as Date, title as Title, company as Company, source as Source, city as City, longitude, latitude FROM offers_view WHERE longitude IS NOT NULL AND latitude IS NOT NULL AND date >= date(:date_start) &date_start=2021-01-01&_shape=objects
```

yields the following JSON output:

```json
{
    "ok": true,
    "database": "jobs",
    "query_name": null,
    "rows": [
        {
            "Date": "2021-04-21",
            "Title": "Devops Python H/F",
            "Company": "Sully Group",
            "Source": "RegionsJob",
            "City": "Aix-en-Provence",
            "longitude": 5.4451153,
            "latitude": 43.5227288
        },
        ...
    ],
    "truncated": true,
    "columns": [
        "Date",
        "Title",
        "Company",
        "Source",
        "City",
        "longitude",
        "latitude"
    ],
    "query": {
        "sql": "SELECT\n  date(date) as Date,\n  title as Title,\n  company as Company,\n  source as Source,\n  city as City,\n  longitude,\n  latitude\nFROM offers_view WHERE longitude IS NOT NULL AND latitude IS NOT NULL\n   AND date >= date(:date_start) \n  \n  \n  ",
        "params": {
            "date_start": "2021-01-01"
        }
    },
    "error": null,
    "private": false,
    "allow_execute_sql": true,
    "query_ms": 6.713455999943108
}
```

## Design

As a reference, Here is how Metabase informs the user with a warning tooltip when the row limit is exceeded:

Screenshot 2023-08-08 at 11 02 32

Screenshot 2023-08-08 at 11 03 42

### PR DESCRIPTION
**Pull request by rclement**
Fixes #144

### CODE REVIEW

**Comment by rclement** [comment]
There seems to be a regression in the dashboard view only: the size of the viewport is extended on the right and an horizontal scroll is available. This might be coming from the tooltip element not playing nice with the global layout...

**Comment by HaveF** [comment]
> There seems to be a regression in the dashboard view only: the size of the viewport is extended on the right and an horizontal scroll is available. This might be coming from the tooltip element not playing nice with the global layout...

I observed that this only appears within a certain window size range. Does it have something to do with reactive layout?

**Comment by rclement** [comment]
> I observed that this only appears within a certain window size range. Does it have something to do with reactive layout?

The reactive layout is automatically handled by the native CSS Grid system, so there is almost nothing we can leverage there.

However, debugging elements overflowing the viewport, the culprit is coming from tooltip text boxes (visible or hidden) on the right-most charts of the grid:

Screenshot 2023-08-17 at 18 02 10

So I need a better way to display tooltips without screwing-up the layout with overflows...

**Comment by rclement** [comment]
Ok so after some digging, here is what I've come up with:

- Preventing overflows and dynamically placing tooltips is **hard** (entire librairies are built for this use-case alone, e.g. [Popper.js](https://popper.js.org/))
- FYI, Metabase is using [Tippy.js](https://atomiks.github.io/tippyjs/), which is overkill for our use case but makes overflow handling a breeze
- The [HTML `title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) is a native way to display tooltips on DOM elements

The `title` attribute is not the sexiest tooltip implementation but is native, requires only HTML (not even CSS not JS) and prevents overflows. So let's use that instead!

**Comment by HaveF** [comment]
@rclement It appears to be a reasonable solution without the need for too many dependencies. I also tested it locally with Vega Lite examples, and there were no issues. 

However, there is one minor problem - the prompts displayed a bit slowly, taking approximately 2 to 3 seconds. At one point, I thought there were no prompts being displayed at all. If this issue is difficult to address, I believe I can still accept it.

**Comment by rclement** [comment]
> ~However, there is one minor problem - the prompts displayed a bit slowly, taking approximately 2 to 3 seconds. At one point, I thought there were no prompts being displayed at all. If this issue is difficult to address, I believe I can still accept it.~ It seems a feature of browser, I believe we can accept it.

The display latency of the tooltip is the main drawback as I see it, but there is nothing we can do about it as this is a per-browser implementation detail, as you observed.

Let's go with that for now, if there is some tooltip wizard in the audience that want to shime in and propose a dependency-free enhancement we'll check it out!

**Pull request merged**
