### PR TITLE
Update README with dashboard layout examples

### PR DESCRIPTION
**Pull request by rclement**
Related to discussion #141

### CODE REVIEW

**Comment by rclement** [comment]
@HaveF I updated the README with more layout instructions and examples, especially the neat feature of CSS grids to specify empty spots within the grid using the `.` (_full stop_) character.
Could you review everything is clearer now?

**Comment by HaveF** [comment]
Do we need to emphasize this:
If a component is not in the layout configuration, it is placed at the end of the entire layout.

**Comment by rclement** [comment]
> Do we need to emphasize this:
> If a component is not in the layout configuration, it is placed at the end of the entire layout.

Mmmh good point. An out-of-grid chart being placed in the lower right corner seems like a bug (I've seen it happen) but it should be more of a layout validation issue (there is none for now).

I've already added a warning concerning the equal number of columns, maybe adding another one that "all charts must be placed on the custom layout"?

**Comment by HaveF** [comment]
LGTM

**Pull request merged**
